apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: 201758385016.dkr.ecr.us-east-1.amazonaws.com/http-api1:latest 
        ports:
        - containerPort: 3001
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydatabase"
        - name: API2_BASE_URL
          value: "http://api2:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: api1
spec:
  type: LoadBalancer # Expose API1 to the internet
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: api1
